import { contentService } from '@/app/api/@types/services';

import {
    BusinessModeling,
    DigitalMarketing,
    DigitalTransformation,
    Finance,
    IndicatorsMetrics,
    InnovationBusinessModel,
    LeanProduction,
    ManagementOKRS,
    Marketing,
    ProductivityTaskManagement,
    QualityProductivity,
    StrategicPlanning
} from '@/components/images';

export const services: contentService[] = [
    {
        title: "Finanças",
        slug: "financas",
        icon: Finance.src,
        bannerImg: "/images/servicos/financas.png",
        description: "Você sabe gerenciar bem o dinheiro da sua empresa? Nós podemos te ajudar! Nossos serviços de finanças oferecem soluções para a gestão eficiente de receitas, despesas, investimentos e fluxo de caixa.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Marketing",
        slug: "marketing",
        icon: Marketing.src,
        bannerImg: "/images/servicos/marketing.png",
        description: "Atrair e fidelizar clientes é fundamental para o sucesso da sua empresa. Com nossos serviços de marketing, você pode criar estratégias e táticas personalizadas para divulgar seus produtos e serviços e alcançar o público certo.",
        content:<>
            <h2>Marketing testando titulo h1</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <h2>Testando Titulo h2</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque</p>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque</p>
            <h3>Testando Titulo h3</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque</p>
            <h4>Testando Titulo h4</h4>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Marketing digital",
        slug: "marketing-digital",
        icon: DigitalMarketing.src,
        bannerImg: "/images/servicos/marketing-digital.png",
        description: "Seu público está online, e você também precisa estar. Nossos serviços de marketing digital utilizam as melhores práticas para explorar canais digitais, alcançar clientes em potencial e gerar resultados reais.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Modelagem de negocios",
        slug: "modelagem-de-negocios",
        icon: BusinessModeling.src,
        bannerImg: "/images/servicos/modelagem-de-negocios.png",
        description: "Você quer entender melhor o seu negócio e identificar oportunidades de crescimento? Nossos serviços de modelagem de negócios podem ajudar a criar e analisar modelos de negócios que vão te ajudar a criar e entregar valor aos seus clientes.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Produção enxuta",
        slug: "producao-enxuta",
        icon: LeanProduction.src,
        bannerImg: "/images/servicos/producao-enxuta.png",
        description: "Você quer reduzir custos e aumentar a eficiência na sua empresa? A produção enxuta é uma abordagem que pode te ajudar. Nossos serviços oferecem soluções para identificar e eliminar desperdícios, simplificar processos e otimizar resultados.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Planejamento estrategico",
        slug: "planejamento-estrategico",
        icon: StrategicPlanning.src,
        bannerImg: "/images/servicos/planejamento-estrategico.png",
        description: "Você quer ter uma visão clara do futuro da sua empresa? O planejamento estratégico é fundamental. Nossos serviços oferecem ferramentas para análise de mercado, definição de metas e objetivos, e elaboração de planos de ação eficazes.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Gestão por OKRS",
        slug: "gestao-por-okrs",
        icon: ManagementOKRS.src,
        bannerImg: "/images/servicos/gestao-por-okrs.png",
        description: "Você quer acompanhar o desempenho da sua empresa e dos seus colaboradores de forma objetiva e eficiente? A gestão por OKRs pode ser a solução. Nossos serviços oferecem ferramentas para definir e acompanhar objetivos e resultados chave, e melhorar a produtividade e a motivação da equipe.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Produtividade e gestão de tarefas",
        slug: "produtividade-e-gestao-de-tarefas",
        icon: ProductivityTaskManagement.src,
        bannerImg: "/images/servicos/produtividade-e-gestao-de-tarefas.png",
        description: "Você quer aumentar a produtividade e a eficiência da sua equipe? Nossos serviços de produtividade e gestão de tarefas oferecem soluções para organizar e priorizar atividades, gerenciar o tempo e evitar desperdícios.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Indicadores e metricas",
        slug: "indicadores-e-metricas",
        icon: IndicatorsMetrics.src,
        bannerImg: "/images/servicos/indicadores-e-metricas.png",
        description: "Você quer acompanhar o desempenho da sua empresa de forma objetiva e precisa? Nossos serviços de indicadores e métricas oferecem soluções para coletar, analisar e interpretar dados relevantes, e tomar decisões estratégicas com base em evidências.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Inovação e Modelo de Negócio",
        slug: "inovacao-e-modelo-de-negocio",
        icon: InnovationBusinessModel.src,
        bannerImg: "/images/servicos/inovacao-e-modelo-de-negocio.png",
        description: "Você quer inovar e encontrar novas oportunidades de crescimento para a sua empresa? Nossos serviços de inovação e modelo de negócio oferecem soluções para identificar tendências de mercado, criar e validar ideias, e implementar modelos de negócios inovadores.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Qualidade e Produtividade",
        slug: "qualidade-e-produtividade",
        icon: QualityProductivity.src,
        bannerImg: "/images/servicos/qualidade-e-produtividade.png",
        description: "Você quer garantir a qualidade dos seus produtos e serviços e aumentar a satisfação dos seus clientes? Nossos serviços de qualidade e produtividade oferecem soluções para identificar oportunidades de melhoria, implementar processos eficazes.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
    {
        title: "Transformação Digital",
        slug: "transformacao-digital",
        icon: DigitalTransformation.src,
        bannerImg: "/images/servicos/transformacao-digital.png",
        description: "Você quer modernizar e otimizar os processos da sua empresa, explorando todo o potencial da tecnologia? A transformação digital pode ser a solução. Descubra como a transformação digital pode trazer mais eficiência, agilidade, inovação e vantagem competitiva para o seu negócio.",
        content:<>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
            <br />
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veritatis voluptatibus amet tempora sit ratione, officiis saepe inventore, doloremque nostrum consequatur cupiditate magni expedita dolorem veniam, eligendi adipisci id quod itaque.</p>
        </>,
    },
];